### ISSUE TITLE
Commenting disabled in activity stream for event published via events calendar pro

### ISSUE THREAD

**Issue by bryanr18lowe** [buddyboss/buddyboss-platform#567]
An option to comment on the activities generated for events via events calendar pro is not available.

-Go to activity settings page in the backend and enable activities for custom post type events
-Click on "activity page"
-Scroll down to any of the events activities
-See no commenting available, only Like or Delete

**Comment by eisenwasser** [comment]
All custom post types need to allow for commenting on their activity posts automatically.

**Comment by eisenwasser** [comment]
@janakkaneriya007 Please prioritize this issue.

**Comment by eisenwasser** [comment]
@bryanr18lowe 

This is resolved in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-3-2/

Now any activity posts creates from custom post types have a Comment button.

**Comment by bryanr18lowe** [comment]
@eisenwasser thanks so much. I appreciate your help to get that fixed. The text editor is a nice addition as well. I am seeing one small conflict where the new icons within the text formatter (dashicons) aren't loading. They're just loading as empty squares. I deactivated wp adverts and it's extension for integrating to bbp or buddy press and the problem still persists. The only other conflicts would be via plugins that you officially support integrations for, i.e. events calendar pro and wp job manager. Are you guys experiencing this on your end?

**Comment by eisenwasser** [comment]
@bryanr18lowe 

Probably you are using User Blog plugin? This is a known conflict, resolved internally. The patch will be released by tomorrow.

Also make sure to clear your cache. Some of the icons used in the editor are newly added, so you want to make sure your browser is seeing the latest icon set.

**Comment by bryanr18lowe** [comment]
@eisenwasser Thanks for this heads up. You're correct. User Blog is the culprit, sorry I didn't think to test your plugins. Thanks again.

**Comment by eisenwasser** [comment]
@bryanr18lowe Ok good to know. That update will come out today or tomorrow.
